### ISSUE TITLE
Should we have any concrete guidelines for who can be a affiliated package reviewer beyond "role holder" + editor discretion?

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-project#101]
This is a side issue from #90 - I didn't want to delay #90 further and figure this can be treated as part of a separate PR if any changes are needed.

#90 updated the affiliated package guidelines, including a part that says reviewers can be either people with roles or other people at the discretion of the editors. This reflect current practice, but seeing it written down makes me realize: do we want to define "other people" in some way - e.g. "must have done at least one PR" or something, or is it OK to leave at the discretion of the editors?

I personally think discretion is better here because it gives room for unusual circumstances, but perhaps @pllim or @hamogu might wish to comment if they think they don't *want* discretion in this setting?

**Comment by astrofrog** [comment]
I think there's several things to consider here - sometimes you might need expertise from someone who e.g. designed an algorithm but knows nothing about astropy. It can be useful to get that person's opinion but I agree that they are not in a good position to review some of the specific criteria we have. So I think we could define who can do the actual main review, which might be more restrictive, while allowing editors to also ask for an *additional* review from literally anyone they might see as relevant?

**Comment by hamogu** [comment]
I agree that in some cases extra expertise might be needed. There are then two possible scenarios (1) the second review is done by another reviewer from the astropy community (2) the astropy-related stuff (interaction with other package etc.) is touched on by the primary reviewer and completed by the editor.

Since this is going to be a rare case (did any case like that happen out of the ~ a dozen packages so far?), I suggest to just leave it at the discretion of the editors. If we don't trust them to do the right decision, then we should chose other editors or leave the job in the hands of the Coco.

If the submitter feels unfairly treated, they can appeal the decision. So, let's start with "no specific" policy and add that later if those cases actually happen in practice and we gain some experience with how it went.

**Comment by hamogu** [comment]
Since there have been no new comments for a while and all comments above agree with the idea that that can be dealt with by "editor discretion", which matches the currently documented rules, I'm going to close this issue.
