### ISSUE TITLE
Call for proposals: Inclusion, Diversity, and Empowerment: FAQ

### ISSUE THREAD

**Issue by aragilar** [astropy/astropy-project#120]
Hi All

The recent call for proposals doesn't seem to specify whether the proposals can come from outside the US. I was thinking of suggesting to the [ASA IDEA chapter](https://asa-idea.org/) that this could be a thing they could get behind, but I wanted to check that this would be possible first.

**Comment by hamogu** [comment]
Proposals can come from anywhere. The money comes from the Moore foundation, which is a private foundation and does not restrict the use of the money to the US. However, the funds are hold in a US bank account, so we cannot transfer them to a country where the US imposes financial sanctions (e.g. Iran, North Korea).

**Comment by bsipocz** [comment]
Can you send a follow up email to make this clear though? The geographical homogeneity wasn't acknowledged in the email and missing out on clearly stating the almost global eligibility is not helping.

**Comment by hamogu** [comment]
I've decided to wait till the weekend is over and see if any more questions come up so that I can answer them together (and point to this issue for any FAQ that come up after that).

**Comment by bsipocz** [comment]
Thank you @hamogu. Saying Western countries is better than saying  nothing, but let's zoom in on the numbers at least here on how much that actually newspeak for the USA.

 75% of the coordinating committee are based in the NE USA and 80% of the finance committee. I don't have the numbers for contributors, but it wouldn't be surprising if ratios of contributors from the EU, Canada, and Australia would not reach their ratio within astronomy.

**Comment by hamogu** [comment]
**Note: Personal statement. Proposals will be discussed by the community, so my opinion is just one of many voices.**

@bsipocz I think it is important to note that we deal with small number statistics though and with people moving around. E.g. even though I'm currently in the US, I did my PhD in Germany and maintain a lot of collaborations there. I think I can claim to understand how German and EU research funding works and what typical working conditions are. On the contrary, I know next to nothing about research work conditions and funding in India or South America. Similarly, I know that another finance committee member is on the way to move to a different continent in the next few weeks, so saying 100% in the US and 80% in the NE of the US is technically true as of today, but does not capture the true problem accurately. 

To put it in other words: Personally, for geographic diversity, I'm not worried about the fact that, e.g. no scientist currently working in Denmark is on either committee, but about the fact that all members both come from "western" countries and work in "western" countries now (though not necessarily the same country).

I'm happy to continue this discussion in more detail, but since "geography" is only one (and one could argue not the most important) of several aspects to inclusion, diversity, and empowerment, I would prefer to have any follow-up discussion in  a different forum.

**Comment by bsipocz** [comment]
I picked on the word western while it should be USA as the original question in the thread was coming from Australia. Which is arguably a part of the world with high participation in astronomy, yet not really connected into the project, while traditionally considered a western country. I nowhere argued for the need of a person from Denmark or any certain countries to be on committees, but it's a very weak argument that one from 5 moving back to Europe will balance out anything even between just those two continents. 


There are zillion reasons why it's like this and all I wanted is to have an acknowledgement of the fact of the NE US centricity and that there is a will in working on changing it. There has been multiple instances of exclusionary behaviour as a result of this, and I'm certain I only know about a subset of those.

So start this work, the bare minimum first step is to state clearly the rules of eligibility, and than has been done now.

**Comment by bsipocz** [comment]
(And it seems that disclaimers are necessary, but to be clear I would be the happiest to see proposals that would extend the project toward Africa, Asia, Australia, and South America and will in fact propose something that can work towards that).

**Comment by manodeep** [comment]
I am glad that the question about eligibility was raised and clarified - it certainly was not clear in the email. And I share the assessment that Australia has a significant Astronomy presence but low participation in the astropy project. 

Might be worthwhile to reach out to projects funded through [IAU OAD](http://www.astro4dev.org/), e.g., [The Pan-African School for Emerging Astronomers](https://www.astrowestafrica.org/)

**Comment by hamogu** [comment]
Since the proposal have been selected, I'm closing this issue.
