### ISSUE TITLE
Annual Report due to Moore Foundation 

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#146]
Finance committee is taking the lead on preparing an annual report to the Moore Foundation. Due Oct 15.

**Comment by hamogu** [comment]
Draft here: Comments welcome. Any substantial comment before Oct 12, typos etc. accepted till Oct 14
https://docs.google.com/document/d/1qF8IiWLlKzZKfAHyqL5Wxwv_2vDxzVG1S65wndyS7es/edit?usp=sharing

**Comment by kelle** [comment]
Based on discussion in #136, I have made some suggestions on the doc to clarify that most of the contracts we made in the past year were for work that folks were already doing. There is only one, the SOSS position, which was dedicated to addressing tasks which were not being sufficiently addressed by existing effort.

**Comment by bsipocz** [comment]
And which task was but sufficiently addressed that the SOSS is solving? I'm really really tired of being called a bottleneck by you when was pouring everything into this project.

**Comment by kelle** [comment]
I see how that phrasing could be hurtful -- I'm so sorry! I guess my interpretation is not that there was a bottleneck, but that this was an area where we could use more hands on deck...too much was falling on too few people. I'll try to rephrase.

**Comment by bsipocz** [comment]
Those 3 examples are fine, and fall into the category of the description, but does any of the other maintainer contract involve being working on bug fixes and reducing the open issues? That is work supposed to be covered by the maintainer role already, but that was a known bottleneck for a long time that volunteer maintainers didn't get to the bottom of. And that's not something the SOSS magic role will suddenly fix, even though it sounds so great on paper and in reports.
 
This is a point what being involved in the dev process would make trivial to see, it's not an accident that the maintainer mentoring was a highlighted priority set by the senior maintainers knowing and acknowledging the bottlenecks around review and triage.

**Comment by hamogu** [comment]
@bsipocz : I remember 3 statement of work on top of my head and all three "are fine". As I said, I would have to re-read the others to pull out concrete examples, but "making live of volunteers easier, help contributors close PRs/issues, and reduce backlog" was definitely on my mind when I reviewed all contracts that we pay for with Moore funding. We did flag two contracts that did not have those points in them. One was reworked and the other one not funded. So, I'm certain that I can answer your question : "does any of the other maintainer contract involve being working on bug fixes and reducing the open issues?" with "yes", but I don't consider it a good use of my time to copy and paste the relevant sentences from each contract into this issue.

However, I also want to remark (but a thorough discussion of that is beyond the scope of this issue) that "number of open issues" alone is not a good criterion for the success of development because issues span a large range of things from serious bugs to feature requests, and reminders for work steps (like "update this last before release") to loose ideas how implementation could be improved. Some of them just linger around, because e.g. they won't ever be fixed because they are only relevant for a numpy version that's going to be dropped in the future anyway or because some upstream library is incompatible for some obscure combination of version and OS. The number of those type of issues will increase with time and with the size of astropy. On the other hand, the number of serious bug should of course be small.  

In fact, I would argue that it was alarming if the number of issues went down significantly, because that means that we would not be generating enough ideas for the future.

I'm sure there is research in the CS community on this phenomenon, but all big libraries that I've seen (numpy, scipy, matplotlib, sherpa, mayavi) have a large number of issues, so astropy is certainly not unusual in that respect.

**Comment by bsipocz** [comment]
No need to pull examples. I don't doubt that all contracts contains useful activities. Yet, I say that they are not addressing the sustainability issues, as critical tasks that hasn't been regularly done before and been identified as a bottlenecks are still not being done. 

Of course, there are issues, I wasn't advocating for a zero issues repo. But it's a very difficult statement to defend that the repo becomes more sustainable by having a ~20% increase in the number of open issues in half a year. 

But there is a surge in the numbers since this spring while the argument was put forward that the grant is there to reduce those and to remove bottlenecks of pr review and triage. So there is a contradiction of what is being said here and in the report (==the grant is for tasks that hasn't been done voluntarily by maintainers, that SOSS is there to address bottlenecks for "timely" PR closure, etc, which is a nonsense as it wasn't the bottleneck in reality just a convenient mantra for those who cared overriden priorities set by the community by spending no time to hear what many of the maintainers were saying. And feedback was given well all the beginning about this, but of course, get ignored with late emails along the line "oh, we ignored the feedback, but here is a tiny point where it's still within what you were suggesting. ",  and now also as pats on backs that how sustainable the project is becoming, while I yet to see numbers that supports that claim.)

**Comment by bsipocz** [comment]
(btw - for the case of mpl and numpy, the effect of their funding is also measurable in the steadyness, or even the descrease of open issues, e.g. the latter has regular, triage calls inlcuding all the paid maintainers as well as their volunteers while for astropy it's quite the opposite. But of course, the funding model they operate with is different.)

**Comment by kelle** [comment]
Submitted report: https://drive.google.com/file/d/1U4hYRdZPOk_J5NoX74WU6dBFf11pQxza/view?usp=sharing
