### ISSUE TITLE
Additional ReadTheDocs feature requests

### ISSUE THREAD

**Issue by jdswinbank** [astropy/astropy-project#249]
Given that we have recently increased the project's donation to Read the Docs (#248), it seems appropriate to consider whether there is additional functionality we could request from them. For inspiration, see the features they make available to commercial customers at https://readthedocs.com/pricing/.

Please add your requests to this issue; the Finance Committee will collate them and coordinate with RtD.

**Comment by pllim** [comment]
Might be useful:

* Search term analytics (90 days)
* Pageview analytics (90 days)

Would this be useful too? Can it provide extra features that our current way of hosting astropy.org cannot?

* Custom domain (docs.yourcompany.com)

**Comment by pllim** [comment]
This one needs Enterprise plan but in case CoCo find it useful:

* Private documentation

**Comment by kelle** [comment]
I am also interested in the analytics. It complements one of the conversations started at the Coordination Meeting. (@jonathansick and @adrn)

**Comment by astrofrog** [comment]
Don't we already have Google Analytics for the RTD documentation? It was set up a while back.

**Comment by eteq** [comment]
FWIW, we don't get *search* analytics, only the pageviews.

**Comment by eteq** [comment]
Given the above, it doesn't seem like there's a lot of appetite right now for specific new features (since the only thing that doesn't seem already addressed via #248 is search analytics, and I'm honestly not sure even I would ever look at that).  So I think it makes sense to close this, although of course someone is always free to open a new issue with a specific request.
