### ISSUE TITLE
astropy admin access for release team

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-project#252]
### Description

There is a need for @astropy/astropy-project-release-team to have admin access to repositories that they will release from. Admin access is necessary to push a commit straight to `main` branch without a pull request. Usually this commit is the same commit that is being tagged for release.

cc @astrofrog and @saimn

**Comment by hamogu** [comment]
I have added this to 
- astropy/astropy (and removed @saimn who had been given admins access individually before, but now has it as part of the release team)
- sphinx-automodapi
- pytest-doctestplus
- pytest-astropy
- sphinx-astropy
- pytest-arraydiff

However, this list is based on repositories that ((I guess might be relevant) AND (https://github.com/orgs/astropy/teams/astropy-project-release-team)) had write permission previously. 

Can you look at the list and let me know which repros I missed, or which ones I should revert, because the release team won't actually make releases for them?

Also, I noted that there are number of packages  (extension-helpers, pytest-openfiles, pytest-filter-subpackage,pytest-remotedata) where https://github.com/orgs/astropy/teams/astropy-project-release-team did not have write permission previously, but that seem to fall in the same category (e.g. why treat pytest-arraydiff different from pytest-openfile ?) I'd to clean that up and make it consistent while we are at it, so if would be great if the release team could put a list of repros here that they intend to work on.

In practice however, there is no hurry since members of the release team are also members of https://github.com/orgs/astropy/teams/testing-infrastructure-maintainers - and that team **does** have admin access to all the intrastructure stuff. However, maybe we don't have the same people on both teams in the future, so let's try to get it right.

**Comment by hamogu** [comment]
I'd still like to get some logic to the sphinx and pytest extensions. Are those going to be released by the astropy-project-release-team or by the testing-infrastructure-maintainers?

**Comment by hamogu** [comment]
So you would suggest we put the release team with write access for the sphinx and pytest extensions, even though that overlaps a bit with testing-infrastructure-maintainers?

**Comment by hamogu** [comment]
OK, I will give the release team write permission for all those. In practice, that means no change for now, because all @astropy/astropy-project-release-team  members are also @astropy/testing-infrastructure-maintainers and thus have write permission so these repros anyway.
