### ISSUE TITLE
Funding Bug Bounties

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#301]
Issue to discuss funding bug bounties, PR #276. [Project Description](https://github.com/astropy/astropy-project/blob/main/finance/proposal-calls/cycle3/bounties.md). Approved 20,000k from Moore.

**Comment by kelle** [comment]
Hi @eteq and @hamogu , this project is good to go from the Finance Committee's side and we look forward to progress on this project!  

When there's a bounty to be paid out, please have them register with Open Collective and [submit an expense to the Moore project](https://opencollective.com/astropy/projects/astropy-moore-8435/expenses/new).

**Comment by hamogu** [comment]
As I had said in an email to the finance committee a while back, I won't be able to organize both #277 and this one and I had suggested to roll this funding into #277 since that addressed a similar concern. In other words, now that #277 is moving forward, I request that the finance committee releases me from the obligation to organize the "bug bounties" program.
