### ISSUE TITLE
Funding Cruz Leadership

### ISSUE THREAD

**Issue by aaryapatil** [astropy/astropy-project#307]
Issue to discuss funding Cruz Leadership, PR #285. [Project Description](https://github.com/astropy/astropy-project/blob/main/finance/proposal-calls/cycle3/kelle-admin.md). $25k for @kelle , funded from the NASA grant (please submit invoices [here](https://opencollective.com/astropy/projects/astropy-nasa)).

**Comment by kelle** [comment]
This funding was for 2022 Summer and if more funds were available, it would be great to also get the 2023 Summer funded so it's more "on cycle" rather than trying to play catchup.  

This funding would support my continued involvement in the Coordination and Finance Committees.

The amount requested will probably be about $15,000, but the exact amount is not certain yet. I should be able to get a firm number by June 5.

**Comment by kelle** [comment]
For 2023, the actual amount I need is $8,394.
| Item | Requested Amount |
|--------|--------|
|   Salary | $5,988 |
|   Summer Fringe (24.6%) | $1,473.05 |
|   F&A (12.5%) | $932.63 |
| **TOTAL**     | **$8,393.68** |

**Comment by aaryapatil** [comment]
This extension request is approved. Please submit expenses to the [Moore budget on Open Collective](https://opencollective.com/astropy/projects/astropy-moore-8435).

**Comment by kelle** [comment]
These funds were received and paid out.
