### ISSUE TITLE
Webserver change: redirect http://www.astropy.org/astroquery/

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-project#322]
This address needs to be redirected to point to the astroquery docs. Those with webserver access (it's anything but transparent who those are) should do it there directly, rather than us downstream hacking around with HTML-level redirects.

**Comment by eteq** [comment]
I'm not exactly sure if this is different from astropy/astropy.github.com#505 or not, but I'm going to assume for now that it's the same topic not a distinct request. 

If I am understanding this correctly, the request is to redirect http://www.astropy.org/astroquery/ to https://astroquery.readthedocs.io/ . http://astropy.org/astroquery/ is a GitHub Pages URL that points to the `gh-pages` branch of `astropy/astroquery`. From context I'm assuming you want "webserver access" because you want to do a 301 or 302-style redirect.  I would love it if someone told me otherwise, but I have not yet found any way that you can configure GitHub Pages to do those kind of redirects. Instead you have to do HTML-level redirects like what https://www.w3.org/TR/WCAG20-TECHS/H76.html says. That would need to happen in the gh-pages branch of `astropy/astroquery` to show up for http://www.astropy.org/astroquery/

An alternative is instead to set up https://astroquery.astropy.org to point to rtd - speculating that this may have been what you wanted, I went ahead and set up https://astroquery.astropy.org to go to the rtd page (although it may take a while for that to propogate throughout the DNS system - usually ~24 hrs). If that is *not* what you ("you" I speculate means @bsipocz , @cdeil , and @keflavich  as the people involved in astropy/astropy.github.com#505) want, please say so and I can turn it back off.

**Comment by eteq** [comment]
Also, I'm also just guessing based on ` (it's anything but transparent who those are)` and the use of the "roles and staffing" label that you are trying to raise a concern that you don't know who to ask this of, @bsipocz .  I just made a PR to clarify that this it is part of the web page maintainer role to maintain the DNS, but since any update of the astroquery page has to be done on the gh-pages branch of `astropy/astroquery`, I presume no further clarification is needed there?

**Comment by bsipocz** [comment]
> An alternative is instead to set up https://astroquery.astropy.org/ to point to rtd

This is exactly what we wanted, removing the outdated content from gh-pages all the while the URL pointing to the actual documentation.

**Comment by bsipocz** [comment]
The redirect is now working, closing.
