### ISSUE TITLE
Travel Funding for Coordination Meeting 

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#336]
### Full name

Kelle Cruz
Tim Pickering
Matt Craig
Aarya Patel

### Description

In-Person participation at the 2023 Astropy Project Coordination Meeting in Cambridge, MA.

### Total request

TBD

### Itemized budget

Each person should provide a budget estimate in this issue.

### Notes
- Itemized meal expenses will be needed.
- Reimbursement requests should be sent to the [Moore project in Open Collective](https://opencollective.com/astropy/projects/astropy-moore-8435/expenses/new).

**Comment by pllim** [comment]
cc @tepickering

**Comment by kelle** [comment]
My budget:
_Lodging:_ ~$1400 at Marriott - ideally paid by PEX card at checkout.
_Travel:_ $183 Amtrak to/from NYC - to be reimbursed.
_Meals:_ ~$200 - actual expenses to be reimbursed.
**ESTIMATED TOTAL = $1,783**

**Comment by tepickering** [comment]
my budget:

- _Lodging:_ ~$1100 at sonder 907 main - actual expense to be reimbursed
- _Travel:_ ~$700 non-redeye airfare - actual expense to be reimbursed
- _Meals:_ ~$200 - actual expenses to be reimbursed
- _Transport:_ ~$50 - personal vehicle 40 miles r/t in tucson, T fares in boston - actual expenses to be reimbursed

ESTIMATED TOTAL = $2350

my lodging estimate is based on a may 1 check-in and may 5 check-out (4 nights) since that is what would be required to fly home on may 5. possible itineraries preclude attending meeting on may 4 and flying home on that day. i will also likely stay in boston longer, but will only submit may 1-5 for reimbursement.

**Comment by hamogu** [comment]
@nstarman If you could post your request for financial assistance here (and a short sentence why it's coming now) that would be great.

**Comment by nstarman** [comment]
My budget:

- lodging: $0, staying with friends
- Travel: CA$580 (~USD$427)
- Transport: $30, (I have a bike rental some days)
- Meals: USD$200 - actual expenses to be reimbursed

ESTIMATED TOTAL = $660

I always wanted to come to the Astropy conference, but didn't I could come due to a family event. My schedule freed up last minute and I would very much like to come in person, especially as a newer maintainer I have not met most Astropy people!

**Comment by kelle** [comment]
Remember, keep itemized meal receipts. When travel is complete, please submit reimbursement request to the [Moore Project in Open Collective](https://opencollective.com/astropy/projects/astropy-moore-8435/expenses/new).
