### ISSUE TITLE
GH Teams Audit: Delete "kcorrect maintainers"

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-project#356]
Does anyone know what this is for? I cannot find any package named kcorrect in the org.

https://github.com/orgs/astropy/teams/kcorrect-maintainers @eteq @ubutsu @okomestudio

**Comment by dhomeier** [comment]
I certainly don't see any overlap between these and the https://github.com/blanton144/kcorrect maintainers, but maybe @weaverba137 as one of the maintainers of the latter knows if there is or was any close connection to Astropy.

**Comment by weaverba137** [comment]
I believe those packages were developed independently, so I would not expect any overlap.

**Comment by pllim** [comment]
Then why do we have our own "kcorrect maintainers" in this org?

**Comment by weaverba137** [comment]
There used to be an astropy-affiliated package called 'kcorrect'. I think it has been archived.

**Comment by pllim** [comment]
I cannot find it anywhere in the org, not even the archived listing.

**Comment by hamogu** [comment]
@eteq is on the team. Unless he has any memory of what this team is meant to do and that use case is current, I second to delete it.

**Comment by weaverba137** [comment]
Then it may have been deleted, but there is a reference to it here: https://github.com/ubutsu/kcorrect/blob/master/README

**Comment by hamogu** [comment]
Or the move was planned, but never actually happened. I don't think that Astropy has ever deleted any repository, we usually archive (unless e.g. a repro is empty because it was made to accommodate some code that was never written).

**Comment by okomestudio** [comment]
Sorry for chiming in late. I was the one who originally wrote the Python binding for Michael Blanton's kcorrect IDL/C library. I always wanted to contribute to astropy, and I asked how a package like this could be part of astropy back then, now more than 10 years ago. And I was told at the time, a package not tightly integrated to astropy would be considered an "affiliated" package. 

I was in the middle of cleaning up/improving the code base for better alignment with the astropy standards, but then my laptop with all the work got stolen and lost the work. The development stopped and kinda didn't proceed since I eventually left academia around the same time, so that may be why few know what this repo is all about.

Believe it or not, I still get a couple of inquiries about the library every now and then, but I'd imagine, with all the progress made in the computing ecosystem, there must be a better alternative for k correction elsewhere now? Then, it may be better to just remove this repo and the maintainer list entirely.

@ubutsu is actually my alternate GitHub account. @okomestudio (this one) is the main one I sue.

**Comment by pllim** [comment]
Team is deleted. There is no repo to archive in this org.

Thank you, everyone!

**Comment by dhomeier** [comment]
Thank you for the clarification and your efforts on integration of `kcorrect` into Astropy @okomestudio!
Sad to hear so much of it is lost, but at this point Michael Blanton's own Python port certainly seems more up to date and maintained, if a new start is required.
