### ISSUE TITLE
Establish a formal users group

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#41]

**Comment by hamogu** [comment]
I think the purpose of a users group in our case should be to poll users who are not in contact with us about what they need form astropy, why they feel intimidated to open issues to participate in the discussions etc. 
The problem is to identify people to serve as a users focus group if by definition they are the people who don't reply on our usual channels. 

Personally, I think a project like astropy does not need a formalized "users group" but rather active contributors reaching out, asking for feedback and reporting second-hand back to the active members. That's done already to so extend (e.g. issues sometimes state " A co-worker of mine not on github experienced the following problem...")

**Comment by pllim** [comment]
Looks like not much buy-in.
