### ISSUE TITLE
Code Review Checklist

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#76]
Do we have a code review checklist? If not, I think we should. Maybe we could just crowdsource this by starting a discussion on astropy-dev asking people what they think should go on the list?

Relevant articles which I skimmed:
- http://blog.smartbear.com/code-review/creating-your-code-review-checklist/
- https://blog.fogcreek.com/increase-defect-detection-with-our-code-review-checklist-example/

**Comment by pllim** [comment]
Documentation of how to do code review should go in https://astropy.readthedocs.io/en/latest/development/workflow/maintainer_workflow.html somewhere.

**Comment by bsipocz** [comment]
Is this for review or PR? the title of the issue and the discussion is ambiguous.  

Also, since the opening of this, we have a PR template, that should have all the pointers for contributors. We still don't have the review checklist, but that's a smaller issue as maintainers are the ones doing the review and they have the gist of it already (having guidelines though useful for onboarding new maintainers)

**Comment by pllim** [comment]
Looks like a duplicate of https://github.com/astropy/astropy-project/issues/212 . See https://github.com/astropy/astropy-project/issues/212#issuecomment-2253297059
