### ISSUE TITLE
Create new role for handling affiliated package submissions

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-project#87]
Until now, I have been handling affiliated package submissions, but will be stepping down from this for the coming year for personal reasons. We should create a formal role for this, and adjust the review process for affiliated package submissions.

The process would be tweaked: the person in the role (the *editor*) would be responsible for looking out for pull requests in the astropy.github.com repository, and search for people who can review the packages. Once they get the review back, they could then take a look at the package themselves and create a final report using the template given in the process documentation. The *editor* would then send this report to the coordination committee for them to take a look at and make a final accept/reject decision, and the *editor* would then post the final review on the pull request.

**Comment by pllim** [comment]
The Affiliator? 😏

**Comment by hamogu** [comment]
I suggest to have the accept/reject decision within the group of editors/affilitors. This is not because I want the affiliators to have all the power, it's  to keep the process streamlined. So I suggest one of two modifications:

(1) The editors/affiliators make a decision and communicate that immediately to the package. That decision can be appealed by contacting the coordination committee (coco). (This is somewhat similar to the process that most journal use.)

(2) The editors send the decision letter to the coco by email. That decision is approved, unless a coco member actively voices disapproval within 72 h.

Personally, I'm in favor of option (1) because it's one step shorter and, let's be honest, the stakes of becoming an affiliated package are not high (you can re-apply later, there is no financial advantage).

**Comment by pllim** [comment]
Note to self: Process currently documented at https://github.com/astropy/project/blob/master/affiliated/affiliated_package_review_process.md#reviewing-affiliated-packages

Item discussed offline: An editor can opt-out if they have a conflict-of-interest with applying package author(s) or institution.

Question: Are editors up for election like TLC? (The election is actively being discussed as part of Astropy Governance meetings.)

**Comment by bsipocz** [comment]
I would think editors are the same category as maintainers. It's a role with one concrete task, so it doesn't necessarily have to be an elected committee.

**Comment by bsipocz** [comment]
Also, option 1) sounds better to me, too, as with option 2) I don't see the task is delegated enough but sneaks back on to the coco's todo and possibly recreates a backlog.

**Comment by hamogu** [comment]
> possibly recreates a backlog

That's why my option 2 has a 72 h timeout.

**Comment by bsipocz** [comment]
> That's why my option 2 has a 72 h timeout.

Yes, I guess that. 

But why put back any revise burden on the top level, when this is a task that could be perfectly delegated. Or the editors are not trusted to have as good judgement about stuff as the coordinators who already have too much other stuff on their plates? Arguably the editors have a good full picture of the ecosystem, coding experience, etc, so it's not an entry level role.

**Comment by pllim** [comment]
Re: 72 h -- If this is really the thing to do, should be documented in #90

**Comment by eteq** [comment]
@pllim @hamogu - note I merged #90 so that those updates get in, but I'm not closing this because it looks like the 72 hr timer is not in there. I'm thinking a follow-on PR on just that could address this, and this issue can be closed either once that's in or we decide it's ok as it stands?

FWIW, I prefer @hamogu's option 2.  One of the roles of the CoCo/TLC has always been to ensure the top-level vision for the Project is followed, and that's why historically the CoCo has held the final say in affiliate role - it's one of the key things that makes the project cohesive.  I think option 2 strikes a good balance between that and the "delegation" element. The CoCo has already had good experience with applying a similar rule "internally", where one member of the CoCo says "I will do this in a few days if no one objects", and it has been a good way to catch mistakes/misunderstandings without adding significant workload burden.

**Comment by pllim** [comment]
Option 2: Would like to amend 72 hr with "X business days" to avoid making people work over weekends and holidays. Also if all the CoCo is on vacation, what happens then?

**Comment by hamogu** [comment]
My understanding is that the 72 h timer is not in there, because we decided that it's not needed. We are going to follow something like that in the transition period (say for the first 5-10 packages), but eventually we want the editors to make the decision. If that's not the case, they should be called "editorial assistants" or "email writers for the coco", not "editors".

**Comment by bsipocz** [comment]
Given I got the mention notification. Feel free to delete the comment, I'm also unsubscribing from the issue after this.

> FWIW, I prefer @hamogu's option 2. One of the roles of the CoCo/TLC has always been to ensure the top-level vision for the Project is followed, and that's why historically the CoCo has held the final say in affiliate role

my 2c, not that anyone cares: maybe it's time to stop acting like the coco/tlc is the sole owner and personal behind the project and the only ones having any clue about the vision, etc. 

Roles are arguably filled with people who are up on speed and knows about the procedures and visions already rather than appointed outsiders. So if a task is delegated, maybe delegate trust as well, so they can do the job well without the constant need for workarounds and wait for the coco to do stuff. A clause like "after reviews, the editors still have the right to seek opinion from the TLC or various astropy voting members" could cover questionable cases, but adding a mandatory 72 hours wait is just another showcase for the status quo that everyone is just a kindergartener who needs constant supervision by the only 4 adults who are the sole holder of the keys.

**Comment by astrofrog** [comment]
I personally don’t think we need to bake in the 72h thing. I think we agreed that for the first few packages the editors will check with the CoCo as a transition thing but really after this the editors should just be trusted to reach out for the CoCo on their own accord if they feel uncertain about a decision. Many cases will be clear cut and not need this. So my vote is to leave the guidelines as is.

**Comment by astrofrog** [comment]
It also occurred to me this is no different to e.g. how subpackage maintainers or coordinated package maintainers don’t have to run every decision past the CoCo even for large PRs. Here if two editors and at least one reviewer who is very familiar with the project guidelines make a decision, I’m happy to trust them :)

**Comment by pllim** [comment]
I think this is done?

**Comment by astrofrog** [comment]
Indeed!
